#!/usr/bin/env python3
from __future__ import annotations
import json, html, os
from pathlib import Path
from typing import Iterable, Dict, Any, List, Optional
from datetime import datetime

# Why not always have jinja2?
try:
    from jinja2 import Environment, FileSystemLoader, select_autoescape, Template
    _HAS_JINJA = True
except Exception:
    _HAS_JINJA = False

def _ensure_parent(p: Path) -> None:
    p.parent.mkdir(parents=True, exist_ok=True)

def append_entries(entries: Iterable[Dict[str, Any]], log_path: Path) -> None:
    """Append entries as JSONL to log_path."""
    _ensure_parent(log_path)
    with log_path.open("a", encoding="utf-8") as f:
        for e in entries:
            f.write(json.dumps(e, ensure_ascii=False) + "\n")

def _read_jsonl(path: Path) -> List[Dict[str, Any]]:
    if not path.exists():
        return []
    rows: List[Dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            s = line.strip()
            if not s:
                continue
            try:
                rows.append(json.loads(s))
            except Exception:
                # skip bad line
                pass
    return rows

def _sort_rows(rows: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    rows.sort(key=lambda r: r.get("acq_ts_sort") or r.get("script_ts") or "", reverse=True)
    return rows

# -------------------------
# Fallback (no Jinja) HTML
# -------------------------
_FALLBACK_CSS = """
  :root { --bg:#0b1020; --card:#11162a; --muted:#94a3b8; --text:#e5e7eb;
          --ok:#10b981; --bad:#ef4444; --na:#6b7280; --accent:#60a5fa; --border:#1f2937; }
  *{box-sizing:border-box}
  body{margin:0;font-family:system-ui,-apple-system,Segoe UI,Roboto,Inter,Ubuntu,"Helvetica Neue",Arial;background:var(--bg);color:var(--text)}
  header{padding:18px 20px;background:linear-gradient(90deg,#0b1020,#0f172a 60%);border-bottom:1px solid var(--border)}
  h1{margin:0;font-weight:700;font-size:18px;letter-spacing:.5px}
  .sub{color:var(--muted);font-size:12px;margin-top:2px}
  .toolbar{display:flex;gap:12px;align-items:center;padding:12px 20px;border-bottom:1px solid var(--border);background:#0d1326}
  .tool{display:flex;gap:8px;align-items:center}
  .tool label{font-size:12px;color:var(--muted)}
  input[type="text"],select{background:#0b1224;color:var(--text);border:1px solid var(--border);border-radius:8px;padding:8px 10px}
  input[type="text"]{min-width:220px}
  .cb{accent-color:var(--accent)}
  .wrap{padding:16px 20px}
  .card{background:var(--card);border:1px solid var(--border);border-radius:14px;overflow:auto;box-shadow:0 10px 30px rgba(0,0,0,.25)}
  table{width:100%;border-collapse:separate;border-spacing:0}
  thead th{position:sticky;top:0;background:#0d1326;border-bottom:1px solid var(--border);padding:10px 12px;font-size:12px;text-align:left;color:var(--muted)}
  tbody td{border-bottom:1px solid var(--border);padding:10px 12px;font-size:13px;vertical-align:top}
  tbody tr:hover{background:#0f1833}
  .nowrap{white-space:nowrap}
  .num{text-align:right;font-variant-numeric:tabular-nums}
  .center{text-align:center}
  .badge{display:inline-block;padding:4px 8px;border-radius:999px;color:#fff;font-size:11px}
  .chip{padding:2px 8px;border-radius:999px;font-size:11px;color:#fff}
  .chip.ok{background:var(--ok)} .chip.bad{background:var(--bad)} .chip.na{background:var(--na)}
  footer{color:var(--muted);font-size:11px;padding:12px 20px}
"""

_FALLBACK_BODY = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>{title}</title>
<style>{css}</style>
</head>
<body>
<header>
  <h1>{title}</h1>
  <div class="sub">Updated {now} • Showing latest {N} entries</div>
</header>
<div class="toolbar">
  <div class="tool"><label for="q">Search</label>
    <input id="q" type="text" placeholder="project, sequence, subject, station…">
  </div>
  <div class="tool"><label for="status">Status</label>
    <select id="status">
      <option value="">All</option>
      <option value="NONCONFORM">Non-conforming</option>
      <option value="NO_TEMPLATE">No template</option>
      <option value="OK">OK</option>
    </select>
  </div>
  <div class="tool"><input id="onlyfail" class="cb" type="checkbox">
    <label for="onlyfail">Only issues</label>
  </div>
</div>
<div class="wrap">
  <div class="card">
    <table id="t">
      <thead>
        <tr>
          <th>Script Time</th><th>Acq Time</th><th>Project</th><th>Sequence</th>
          <th>Subject</th><th>Series</th><th>Station</th><th>Conforms</th>
          <th>Errors</th><th>Error Detail</th><th>Status</th>
        </tr>
      </thead>
      <tbody>
        {rows_html}
      </tbody>
    </table>
  </div>
</div>
<footer>DB entries are appended to a JSONL log and this page is regenerated by the MRQART job.</footer>
<script>
  const q = document.getElementById('q');
  const statusSel = document.getElementById('status');
  const onlyFail = document.getElementById('onlyfail');
  const tbody = document.querySelector('#t tbody');
  function matches(row, needle) {{
    if (!needle) return true;
    const txt = row.innerText.toLowerCase();
    return txt.includes(needle);
  }}
  function show(row, ok) {{ row.style.display = ok ? '' : 'none'; }}
  function applyFilters() {{
    const needle = q.value.trim().toLowerCase();
    const status = statusSel.value;
    const rows = Array.from(tbody.querySelectorAll('tr'));
    rows.forEach(r => {{
      const st = r.getAttribute('data-status') || '';
      const matchesStatus = !status || st === status;
      const hasIssue = (st === 'NONCONFORM' || st === 'NO_TEMPLATE');
      const wantIssues = !onlyFail.checked || hasIssue;
      show(r, matches(r, needle) && matchesStatus && wantIssues);
    }});
  }}
  q.addEventListener('input', applyFilters);
  statusSel.addEventListener('change', applyFilters);
  onlyFail.addEventListener('change', applyFilters);
</script>
</body>
</html>
"""

def _badge_bool(b) -> str:
    if b is True:  return '<span class="chip ok">True</span>'
    if b is False: return '<span class="chip bad">False</span>'
    return '<span class="chip na">N/A</span>'

def _status_badge(s: str) -> str:
    color = {"OK":"#10b981","NONCONFORM":"#ef4444","NO_TEMPLATE":"#f59e0b"}.get(s, "#6b7280")
    return f'<span class="badge" style="background:{color};">{html.escape(s or "")}</span>'

def _fmt_errs(errs) -> str:
    if not errs: return ""
    if isinstance(errs, str): return html.escape(errs)
    return "<ul>" + "".join(f"<li>{html.escape(str(e))}</li>" for e in errs) + "</ul>"

def _render_fallback(rows: List[Dict[str, Any]], html_out: Path, title: str) -> None:
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    trs = []
    for r in rows:
        trs.append(
            f"""<tr data-status="{html.escape(str(r.get('status','')))}">
  <td class="nowrap">{html.escape(str(r.get('script_ts','')))}</td>
  <td class="nowrap">{html.escape(str(r.get('acq_ts','')))}</td>
  <td>{html.escape(str(r.get('project','')))}</td>
  <td>{html.escape(str(r.get('sequence','')))}</td>
  <td>{html.escape(str(r.get('subid','')))}</td>
  <td class="num">{html.escape(str(r.get('series','')))}</td>
  <td>{html.escape(str(r.get('station','')))}</td>
  <td class="center">{_badge_bool(r.get('conforms'))}</td>
  <td class="num">{html.escape(str(r.get('error_count','')))}</td>
  <td>{_fmt_errs(r.get('errors'))}</td>
  <td>{_status_badge(str(r.get('status','')))}</td>
</tr>"""
        )
    out = _FALLBACK_BODY.format(
        title=html.escape(title),
        css=_FALLBACK_CSS,
        now=html.escape(now),
        N=len(rows),
        rows_html="\n".join(trs),
    )
    _ensure_parent(html_out)
    html_out.write_text(out, encoding="utf-8")

# -------------------------
# Public: render_html
# -------------------------
def render_html(
    log_path: Path,
    html_out: Path,
    title: str = "MRQART QA — Feed",
    max_rows: int = 2000,
    template_path: Optional[Path] = None,
) -> None:
    """
    Render a static HTML from JSONL log.
    If Jinja2 is available and a template is found, render with Jinja.
    Otherwise fall back to the built-in renderer (same look as before).
    """
    rows = _read_jsonl(log_path)
    rows = _sort_rows(rows)
    if max_rows and len(rows) > max_rows:
        rows = rows[:max_rows]

    if _HAS_JINJA:
        # Resolve template: env var > passed path > default in static/
        tpl_env = os.environ.get("MRQART_WEB_TEMPLATE")
        tpl_file = Path(tpl_env) if tpl_env else None
        if not tpl_file and template_path:
            tpl_file = Path(template_path)
        if not tpl_file:
            # Default location: <repo>/static/mrqart_report.html.j2
            tpl_file = Path(__file__).resolve().parent.parent / "static" / "mrqart_report.html.j2"

        if tpl_file.exists():
            # Jinja environment pointing at template directory
            loader = FileSystemLoader(str(tpl_file.parent))
            env = Environment(loader=loader, autoescape=select_autoescape(["html", "xml"]))
            tmpl: Template = env.get_template(tpl_file.name)

            ctx = {
                "title": title,
                "rows": rows,
                "updated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "count": len(rows),
            }
            _ensure_parent(html_out)
            html_out.write_text(tmpl.render(**ctx), encoding="utf-8")
            return
        # else: fall through to fallback if template missing

    # Fallback path: no Jinja or template not found
    _render_fallback(rows, html_out, title)

